# Amira Project 201920
# Amira
# Generated by Amira 2019.2
remove -all
set parameter $::param
remove "grayScale.am" "labels.am" ${param} "DeanLab01-18-18.binary" "Result" "Result.closing" "Result.labels" "Result.filtered" "Result.Label-Analysis" "Result.opening" "Result2" "Result2.surf" "DataDirectory_DeanLab01-18-18" "Ortho Slice" "Hysteresis Thresholding" "DataDirectory_DeanLab01-18-18.binary" "DataDirectory_Result" "Closing" "DataDirectory_Result.closing" "Labeling" "Filter by Measure Range" "DataDirectory_Result.labels" "Filter by Measure" "DataDirectory_Result.filtered" "Volume Rendering Settings" "Voxelized Rendering" "Label Analysis" "DataDirectory_Result.Label-Analysis" "Extract Subvolume" "Generate Surface" "Extract Subvolume 2" "DataDirectory_grayScale.am" "DataDirectory_labels.am" "Selective Opening" "DataDirectory_Result.opening" "Volume Rendering Settings 2" "Voxelized Rendering 2" "Arithmetic" "DataDirectory_Result2" "DataDirectory_Result2.surf" "Surface View" "Ortho Slice 2"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

_units setUnitsManagementMode 0

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/labels.am ] setLabel "labels.am"
"labels.am" setIconPosition 0 0
"labels.am" setNoRemoveAll 1
"labels.am" setVar "CustomHelp" {HxColormap256}
"labels.am" fire
"labels.am" setMinMax 1 8
"labels.am" flags setValue 1
"labels.am" shift setMinMax -1 1
"labels.am" shift setButtons 0
"labels.am" shift setEditButton 1
"labels.am" shift setIncrement 0.133333
"labels.am" shift setValue 0
"labels.am" shift setSubMinMax -1 1
"labels.am" scale setMinMax 0 1
"labels.am" scale setButtons 0
"labels.am" scale setEditButton 1
"labels.am" scale setIncrement 0.1
"labels.am" scale setValue 1
"labels.am" scale setSubMinMax 0 1
"labels.am" fire
"labels.am" setViewerMask 16383

set hideNewModules 0
[ load -unit µm -tif +mode 100 +box 0 19929 0 19929 0 <Z_SIZE> ${SCRIPTDIR}/../samples/<PC001_STEM>.ome.tif ] setLabel "<PC001_STEM>.ome.tif"

[ load ${SCRIPTDIR}/${param}_DICOM.am ] setLabel "${param}_DICOM"
"${param}_DICOM" setIconPosition 20 10
"${param}_DICOM" sharedColormap disconnect
"${param}_DICOM" sharedColormap setDefaultColor 0.8 0.8 0.8
"${param}_DICOM" sharedColormap setDefaultAlpha 0.500000
"${param}_DICOM" sharedColormap activateLocalRange 1
"${param}_DICOM" sharedColormap setLocalMinMax 0.000000 1.000000
"${param}_DICOM" sharedColormap enableAlpha 1
"${param}_DICOM" sharedColormap enableAlphaToggle 1
"${param}_DICOM" sharedColormap setAutoAdjustRangeMode 1
"${param}_DICOM" fire
"${param}_DICOM" fire
"${param}_DICOM" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_${param}_DICOM"
"DataDirectory_${param}_DICOM" setIconPosition 0 0
"DataDirectory_${param}_DICOM" setInvisible 1
"DataDirectory_${param}_DICOM" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_${param}_DICOM" parentDir connect "Data"
"DataDirectory_${param}_DICOM" attachedData connect "${param}_DICOM"
"DataDirectory_${param}_DICOM" fire
"DataDirectory_${param}_DICOM" setViewerMask 16383


set hideNewModules 0
create hysteresis "Hysteresis Thresholding"
"Hysteresis Thresholding" setIconPosition 160 46
"Hysteresis Thresholding" setVar "CustomHelp" {hysteresis.html}
"Hysteresis Thresholding" interpretation setValue 0
"Hysteresis Thresholding" outputLocation setIndex 0 0
"Hysteresis Thresholding" inputImage connect "${param}_DICOM"
"Hysteresis Thresholding" thresholds setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Hysteresis Thresholding" thresholds setValue 0 100
"Hysteresis Thresholding" thresholds setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Hysteresis Thresholding" thresholds setValue 1 500
"Hysteresis Thresholding" length setMinMax 0 0 2147483648
"Hysteresis Thresholding" length setValue 0 3
"Hysteresis Thresholding" applyTransformToResult 1
"Hysteresis Thresholding" fire
"Hysteresis Thresholding" setViewerMask 16383
"Hysteresis Thresholding" setPickable 1

set hideNewModules 0
[ {Hysteresis Thresholding} create ImgOutBin ] setLabel "${param}.binary"
"${param}.binary" setIconPosition 20 82
"${param}.binary" master connect "Hysteresis Thresholding" "ImgOutBin" 0
"${param}.binary" sharedColormap connect "labels.am"
"${param}.binary" sharedColormap setDefaultColor 0.8 0.8 0.8
"${param}.binary" sharedColormap setDefaultAlpha 0.500000
"${param}.binary" sharedColormap activateLocalRange 1
"${param}.binary" sharedColormap setLocalMinMax 1.000000 8.000000
"${param}.binary" sharedColormap enableAlpha 1
"${param}.binary" sharedColormap enableAlphaToggle 1
"${param}.binary" sharedColormap setAutoAdjustRangeMode 1
"${param}.binary" sharedColormap setColorbarMinMax 0 120
"${param}.binary" fire
"${param}.binary" primary setIndex 0 0
"${param}.binary" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"${param}.binary" fire
"${param}.binary" setViewerMask 49151

set hideNewModules 1
create HxDataDirectory "DataDirectory_${param}.binary"
"DataDirectory_${param}.binary" setIconPosition 0 0
"DataDirectory_${param}.binary" setInvisible 1
"DataDirectory_${param}.binary" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_${param}.binary" parentDir connect "Data"
"DataDirectory_${param}.binary" attachedData connect "${param}.binary"
"DataDirectory_${param}.binary" fire
"DataDirectory_${param}.binary" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_grayScale.am"
"DataDirectory_grayScale.am" setIconPosition 0 0
"DataDirectory_grayScale.am" setNoRemoveAll 1
"DataDirectory_grayScale.am" setInvisible 1
"DataDirectory_grayScale.am" parentDir connect "Colormaps"
"DataDirectory_grayScale.am" attachedData connect "grayScale.am"
"DataDirectory_grayScale.am" fire
"DataDirectory_grayScale.am" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_labels.am"
"DataDirectory_labels.am" setIconPosition 0 0
"DataDirectory_labels.am" setNoRemoveAll 1
"DataDirectory_labels.am" setInvisible 1
"DataDirectory_labels.am" parentDir connect "Colormaps"
"DataDirectory_labels.am" attachedData connect "labels.am"
"DataDirectory_labels.am" fire
"DataDirectory_labels.am" setViewerMask 16383

set hideNewModules 0
create selectiveopening2d "Selective Opening"
"Selective Opening" setIconPosition 160 540
"Selective Opening" setVar "CustomHelp" {selectiveopening3d.html}
"Selective Opening" interpretation setValue 0
"Selective Opening" outputLocation setIndex 0 0
"Selective Opening" inputBinaryImage connect "${param}.binary"
"Selective Opening" numberOfIterations setMinMax 0 1 2147483648
"Selective Opening" numberOfIterations setValue 0 3
"Selective Opening" threshold setMinMax 0 1 26
"Selective Opening" threshold setValue 0 1
"Selective Opening" applyTransformToResult 1
"Selective Opening" fire
"Selective Opening" setViewerMask 16383
"Selective Opening" setPickable 1

set hideNewModules 0
[ {Selective Opening} create ImgOut ] setLabel "Result.opening"
"Result.opening" setIconPosition 20 540
"Result.opening" master connect "Selective Opening" "ImgOut" 0
"Result.opening" sharedColormap connect "labels.am"
"Result.opening" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result.opening" sharedColormap setDefaultAlpha 0.500000
"Result.opening" sharedColormap activateLocalRange 1
"Result.opening" sharedColormap setLocalMinMax 1.000000 8.000000
"Result.opening" sharedColormap enableAlpha 1
"Result.opening" sharedColormap enableAlphaToggle 1
"Result.opening" sharedColormap setAutoAdjustRangeMode 1
"Result.opening" sharedColormap setColorbarMinMax 1 8
"Result.opening" fire
"Result.opening" primary setIndex 0 0
"Result.opening" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result.opening" fire
"Result.opening" setViewerMask 16383

set hideNewModules 0
create sphereclosing3d "Closing"
"Closing" setIconPosition 160 154
"Closing" setVar "CustomHelp" {sphereclosing3d.html}
"Closing" Type setState {type Ball}
"Closing" interpretation setValue 0
"Closing" outputLocation setIndex 0 0
"Closing" inputImage connect "Result.opening"
"Closing" size setMinMax 0 1 2147483648
"Closing" size setValue 0 20
"Closing" precision setIndex 0 0
"Closing" applyTransformToResult 1
"Closing" fire
"Closing" setViewerMask 16383
"Closing" setPickable 1

set hideNewModules 0
[ {Closing} create ImgOut ] setLabel "Result.closing"
"Result.closing" setIconPosition 20 216
"Result.closing" master connect "Closing" "ImgOut" 0
"Result.closing" sharedColormap connect "labels.am"
"Result.closing" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result.closing" sharedColormap setDefaultAlpha 0.500000
"Result.closing" sharedColormap activateLocalRange 1
"Result.closing" sharedColormap setLocalMinMax 1.000000 8.000000
"Result.closing" sharedColormap enableAlpha 1
"Result.closing" sharedColormap enableAlphaToggle 1
"Result.closing" sharedColormap setAutoAdjustRangeMode 1
"Result.closing" sharedColormap setColorbarMinMax 0 120
"Result.closing" fire
"Result.closing" primary setIndex 0 0
"Result.closing" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result.closing" fire
"Result.closing" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_Result.closing"
"DataDirectory_Result.closing" setIconPosition 0 0
"DataDirectory_Result.closing" setInvisible 1
"DataDirectory_Result.closing" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_Result.closing" parentDir connect "Data"
"DataDirectory_Result.closing" attachedData connect "Result.closing"
"DataDirectory_Result.closing" fire
"DataDirectory_Result.closing" setViewerMask 16383

set hideNewModules 0
create label "Labeling"
"Labeling" setIconPosition 160 252
"Labeling" setVar "CustomHelp" {label.html}
"Labeling" interpretation setValue 0
"Labeling" outputLocation setIndex 0 0
"Labeling" neighborhood setValue 2
"Labeling" inputImage connect "Result.closing"
"Labeling" applyTransformToResult 1
"Labeling" fire
"Labeling" setViewerMask 16383
"Labeling" setPickable 1

set hideNewModules 0
[ {Labeling} create ImgOutLab ] setLabel "Result.labels"
"Result.labels" setIconPosition 20 252
"Result.labels" master connect "Labeling" "ImgOutLab" 0
"Result.labels" sharedColormap connect "labels.am"
"Result.labels" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result.labels" sharedColormap setDefaultAlpha 0.500000
"Result.labels" sharedColormap activateLocalRange 1
"Result.labels" sharedColormap setLocalMinMax 1.000000 8.000000
"Result.labels" sharedColormap enableAlpha 1
"Result.labels" sharedColormap enableAlphaToggle 1
"Result.labels" sharedColormap setAutoAdjustRangeMode 1
"Result.labels" sharedColormap setColorbarMinMax 0 120
"Result.labels" fire
"Result.labels" primary setIndex 0 0
"Result.labels" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result.labels" fire
"Result.labels" setViewerMask 16383

set hideNewModules 0
create HxFilterMeasureRange "Filter by Measure Range"
"Filter by Measure Range" setIconPosition 160 216
"Filter by Measure Range" setVar "CustomHelp" {HxFilterMeasureRange}
"Filter by Measure Range" data connect "Result.labels"
"Filter by Measure Range" fire
"Filter by Measure Range" interpretation setValue 0
labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
labelMeasure setAttributes feret3d 31
labelMeasure setAttributes cooccurrence 0 0
labelMeasure setAttributes histogram 1 0 255 1
labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
labelMeasure setAttributes breadth3d 10
labelMeasure setAttributes neighborCount 0 5 0
"Filter by Measure Range" measure setState {Volume}
"Filter by Measure Range" fire
"Filter by Measure Range" range setMinMax 0 8509470
"Filter by Measure Range" range setValues 100000 8.50947e+006
"Filter by Measure Range" range setButtons 0
"Filter by Measure Range" range setEditButton 1
"Filter by Measure Range" range setIncrement 567298
"Filter by Measure Range" range setSubMinMax 0 0
"Filter by Measure Range" applyTransformToResult 1
"Filter by Measure Range" fire
"Filter by Measure Range" setViewerMask 16383
"Filter by Measure Range" setPickable 1

set hideNewModules 0
[ {Filter by Measure Range} create result ] setLabel "Result.filtered"
"Result.filtered" setIconPosition 20 324
"Result.filtered" master connect "Filter by Measure Range" "result" 0
"Result.filtered" sharedColormap connect "labels.am"
"Result.filtered" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result.filtered" sharedColormap setDefaultAlpha 0.500000
"Result.filtered" sharedColormap activateLocalRange 1
"Result.filtered" sharedColormap setLocalMinMax 1.000000 8.000000
"Result.filtered" sharedColormap enableAlpha 1
"Result.filtered" sharedColormap enableAlphaToggle 1
"Result.filtered" sharedColormap setAutoAdjustRangeMode 1
"Result.filtered" sharedColormap setColorbarMinMax 0 120
"Result.filtered" fire
"Result.filtered" primary setIndex 0 0
"Result.filtered" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result.filtered" fire
"Result.filtered" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_Result.labels"
"DataDirectory_Result.labels" setIconPosition 0 0
"DataDirectory_Result.labels" setInvisible 1
"DataDirectory_Result.labels" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_Result.labels" parentDir connect "Data"
"DataDirectory_Result.labels" attachedData connect "Result.labels"
"DataDirectory_Result.labels" fire
"DataDirectory_Result.labels" setViewerMask 16383

set hideNewModules 0
create measurefilter "Filter by Measure"
"Filter by Measure" setIconPosition 160 288
"Filter by Measure" setVar "CustomHelp" {measurefilter.html}
"Filter by Measure" interpretation setValue 0
"Filter by Measure" outputLocation setIndex 0 0
"Filter by Measure" inputImage connect "Result.labels"
"Filter by Measure" inputIntensityImage connect "${param}_DICOM"
labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
labelMeasure setAttributes feret3d 31
labelMeasure setAttributes cooccurrence 0 0
labelMeasure setAttributes histogram 1 0 255 1
labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
labelMeasure setAttributes breadth3d 10
labelMeasure setAttributes neighborCount 0 5 0
"Filter by Measure" measure setState {Volume}
"Filter by Measure" measureFilterType setIndex 0 0
"Filter by Measure" numberOfPatterns setMinMax 0 1 2147483648
"Filter by Measure" numberOfPatterns setValue 0 11
"Filter by Measure" applyTransformToResult 1
"Filter by Measure" fire
"Filter by Measure" setViewerMask 16383
"Filter by Measure" setPickable 1

set hideNewModules 1
create HxDataDirectory "DataDirectory_Result.filtered"
"DataDirectory_Result.filtered" setIconPosition 0 0
"DataDirectory_Result.filtered" setInvisible 1
"DataDirectory_Result.filtered" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_Result.filtered" parentDir connect "Data"
"DataDirectory_Result.filtered" attachedData connect "Result.filtered"
"DataDirectory_Result.filtered" fire
"DataDirectory_Result.filtered" setViewerMask 16383

set hideNewModules 0
create HxVolumeRenderingSettings "Volume Rendering Settings"
"Volume Rendering Settings" setViewerMask 0
"Volume Rendering Settings" setIconPosition -103 118
"Volume Rendering Settings" setVar "CustomHelp" {HxVolumeRenderingSettings}
set hideNewModules 0

"Volume Rendering Settings" data connect "Result.filtered"
"Volume Rendering Settings" fire
"Volume Rendering Settings" rendering setValue 0
"Volume Rendering Settings" fire
"Volume Rendering Settings" interpolationAdvanced setValue 0
"Volume Rendering Settings" composition setValue 0
"Volume Rendering Settings" moveLowResolutionScale setMinMax 1 10
"Volume Rendering Settings" moveLowResolutionScale setButtons 1
"Volume Rendering Settings" moveLowResolutionScale setEditButton 1
"Volume Rendering Settings" moveLowResolutionScale setIncrement 1
"Volume Rendering Settings" moveLowResolutionScale setValue 2
"Volume Rendering Settings" moveLowResolutionScale setSubMinMax 1 10
"Volume Rendering Settings" samplingQuality setMinMax 0 2
"Volume Rendering Settings" samplingQuality setButtons 0
"Volume Rendering Settings" samplingQuality setEditButton 1
"Volume Rendering Settings" samplingQuality setIncrement 0.133333
"Volume Rendering Settings" samplingQuality setValue 1
"Volume Rendering Settings" samplingQuality setSubMinMax 0 2
"Volume Rendering Settings" opacityThreshold setMinMax 0 1
"Volume Rendering Settings" opacityThreshold setButtons 0
"Volume Rendering Settings" opacityThreshold setEditButton 1
"Volume Rendering Settings" opacityThreshold setIncrement 0.05
"Volume Rendering Settings" opacityThreshold setValue 0
"Volume Rendering Settings" opacityThreshold setSubMinMax 0 1
"Volume Rendering Settings" optimizations setValue 0 0
"Volume Rendering Settings" optimizations setToggleVisible 0 1
"Volume Rendering Settings" optimizations setValue 1 1
"Volume Rendering Settings" optimizations setToggleVisible 1 1
"Volume Rendering Settings" optimizations setValue 2 0
"Volume Rendering Settings" optimizations setToggleVisible 2 1
"Volume Rendering Settings" quality setValue 3
"Volume Rendering Settings" fire
"Volume Rendering Settings" artifactsReduction setValue 0 0
"Volume Rendering Settings" artifactsReduction setToggleVisible 0 1
"Volume Rendering Settings" artifactsReduction setValue 1 0
"Volume Rendering Settings" artifactsReduction setToggleVisible 1 1
"Volume Rendering Settings" lighting setState {item 0 1 item 1 1 }
"Volume Rendering Settings" gradient setState {item 0 1 item 2 9.99999974737875e-05 }
"Volume Rendering Settings" effects setValue 0 0
"Volume Rendering Settings" effects setToggleVisible 0 1
"Volume Rendering Settings" effects setValue 1 0
"Volume Rendering Settings" effects setToggleVisible 1 1
"Volume Rendering Settings" effects setValue 2 0
"Volume Rendering Settings" effects setToggleVisible 2 1
"Volume Rendering Settings" effects setValue 3 1
"Volume Rendering Settings" effects setToggleVisible 3 1
"Volume Rendering Settings" edgeEnhancement setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Volume Rendering Settings" edgeEnhancement setValue 0 9.99999974737875e-005
"Volume Rendering Settings" edge2D setState {item 1 0.100000001490116 item 3 0.100000001490116 item 5 1 }
"Volume Rendering Settings" boundaryOpacity setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Volume Rendering Settings" boundaryOpacity setValue 0 2.5
"Volume Rendering Settings" boundaryOpacity setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Volume Rendering Settings" boundaryOpacity setValue 1 2.5
"Volume Rendering Settings" material setIndex 0 4
"Volume Rendering Settings" lightingStyle setIndex 0 1
"Volume Rendering Settings" toneMapping setIndex 0 0
"Volume Rendering Settings" depthOfField setValue 0
"Volume Rendering Settings" blurFactor setMinMax 0.00999999977648258 1
"Volume Rendering Settings" blurFactor setButtons 0
"Volume Rendering Settings" blurFactor setEditButton 1
"Volume Rendering Settings" blurFactor setIncrement 0.066
"Volume Rendering Settings" blurFactor setValue 0.01
"Volume Rendering Settings" blurFactor setSubMinMax 0.00999999977648258 1
"Volume Rendering Settings" specularColor setMinMax 0 1
"Volume Rendering Settings" specularColor setButtons 0
"Volume Rendering Settings" specularColor setEditButton 1
"Volume Rendering Settings" specularColor setIncrement 0.1
"Volume Rendering Settings" specularColor setValue 0.4
"Volume Rendering Settings" specularColor setSubMinMax 0 1
"Volume Rendering Settings" shininess setMinMax 0 1
"Volume Rendering Settings" shininess setButtons 0
"Volume Rendering Settings" shininess setEditButton 1
"Volume Rendering Settings" shininess setIncrement 0.1
"Volume Rendering Settings" shininess setValue 0.4
"Volume Rendering Settings" shininess setSubMinMax 0 1
"Volume Rendering Settings" fire
"Volume Rendering Settings" setViewerMask 16383
"Volume Rendering Settings" setPickable 1

set hideNewModules 0
create HxVoxelizedRender "Voxelized Rendering"
"Voxelized Rendering" setIconPosition -103 144
"Voxelized Rendering" setVar "CustomHelp" {HxVoxelizedRender}
"Voxelized Rendering" data connect "Result.filtered"
"Voxelized Rendering" volumeRenderingSettings connect "Volume Rendering Settings"
"Voxelized Rendering" fire
"Voxelized Rendering" colormap connect "labels.am"
"Voxelized Rendering" colormap setDefaultColor 1 1 1
"Voxelized Rendering" colormap setDefaultAlpha 0.500000
"Voxelized Rendering" colormap activateLocalRange 1
"Voxelized Rendering" colormap setLocalMinMax 1.000000 8.000000
"Voxelized Rendering" colormap enableAlpha 1
"Voxelized Rendering" colormap enableAlphaToggle 1
"Voxelized Rendering" colormap setAutoAdjustRangeMode 1
"Voxelized Rendering" fire
"Voxelized Rendering" colormapLookup setValue 2
"Voxelized Rendering" gamma setMinMax 0.100000001490116 8
"Voxelized Rendering" gamma setButtons 0
"Voxelized Rendering" gamma setEditButton 1
"Voxelized Rendering" gamma setIncrement 0.526667
"Voxelized Rendering" gamma setValue 3
"Voxelized Rendering" gamma setSubMinMax 0.100000001490116 8
"Voxelized Rendering" alphaScale setMinMax 0 1
"Voxelized Rendering" alphaScale setButtons 0
"Voxelized Rendering" alphaScale setEditButton 1
"Voxelized Rendering" alphaScale setIncrement 0.1
"Voxelized Rendering" alphaScale setValue 1
"Voxelized Rendering" alphaScale setSubMinMax 0 1
"Voxelized Rendering" channelSelector setState {2 }
"Voxelized Rendering" outline setValue 0 0
"Voxelized Rendering" outline setToggleVisible 0 1
"Voxelized Rendering" fire
"Voxelized Rendering" setViewerMask 16383
"Voxelized Rendering" setPickable 1


"VoxelizedRendering" fire
"VolumeRenderingSettings" fire

viewer setCameraOrientation 1 0 0 3.14159
viewer setCameraPosition 18.0075 17.1675 -18.0989
viewer setCameraFocalDistance 48.4754
viewer setCameraNearDistance 45.0853
viewer setCameraFarDistance 51.8722
viewer setCameraType perspective
viewer setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

set LDAexpertsettings [create HxLDAExpertSettings]
"LDAExpertSettings" fixedResolution setValue 0 1
"LDAExpertSettings" fixedResolutionLevel setValue 0 0
"LDAExpertSettings" fire

set hideNewModules 0
create HxAnalyzeLabels "Label Analysis"
"Label Analysis" setIconPosition 160 324
"Label Analysis" setVar "CustomHelp" {HxAnalyzeLabels}
"Label Analysis" data connect "Result.filtered"
"Label Analysis" fire
"Label Analysis" interpretation setValue 0
"Label Analysis" sequenceMode setValue 0
"Label Analysis" intensityImage connect "${param}_DICOM"
labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
labelMeasure setAttributes feret3d 31
labelMeasure setAttributes cooccurrence 0 0
labelMeasure setAttributes histogram 1 0 255 1
labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
labelMeasure setAttributes breadth3d 10
labelMeasure setAttributes neighborCount 0 5 0
"Label Analysis" measures setState {"Geometry"}
"Label Analysis" showAnalysis setValue 0 1
"Label Analysis" showAnalysis setToggleVisible 0 1
"Label Analysis" applyTransformToResult 1
"Label Analysis" fire
"Label Analysis" setViewerMask 16383
"Label Analysis" setPickable 1

set hideNewModules 0
[ {Label Analysis} create AnlOut ] setLabel "Result.Label-Analysis"
"Result.Label-Analysis" setIconPosition 20 360
"Result.Label-Analysis" master connect "Label Analysis" "AnlOut" 0
"Result.Label-Analysis" fire
"Result.Label-Analysis" fire
"Result.Label-Analysis" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_Result.Label-Analysis"
"DataDirectory_Result.Label-Analysis" setIconPosition 0 0
"DataDirectory_Result.Label-Analysis" setInvisible 1
"DataDirectory_Result.Label-Analysis" setVar "CustomHelp" {HxDataDirectory}
"DataDirectory_Result.Label-Analysis" parentDir connect "Data"
"DataDirectory_Result.Label-Analysis" attachedData connect "Result.Label-Analysis"
"DataDirectory_Result.Label-Analysis" fire
"DataDirectory_Result.Label-Analysis" setViewerMask 16383

set hideNewModules 1
create HxDataDirectory "DataDirectory_Result.opening"
"DataDirectory_Result.opening" setIconPosition 0 0
"DataDirectory_Result.opening" setInvisible 1
"DataDirectory_Result.opening" parentDir connect "Data"
"DataDirectory_Result.opening" attachedData connect "Result.opening"
"DataDirectory_Result.opening" fire
"DataDirectory_Result.opening" setViewerMask 16383

"Result.Label-Analysis" exportData "csv"  D:/data/MDean/MDean_baculae.${param}.label_analysis.csv
"Voxelized Rendering" alphaScale setValue 0.2
"Voxelized Rendering" fire
"Voxelized Rendering" alphaScale setValue 1
"Voxelized Rendering" fire
viewer snapshot -offscreen 640 640 D:/data/MDean/${param}.label.overview.png

remove "Result2_Medulla"
remove "Opening_Medulla"

Result.Label-Analysis table hit
Result.Label-Analysis fire

"Voxelized Rendering" colormapLookup setValue 0
"Voxelized Rendering" alphaScale setValue 0.2
"Voxelized Rendering" fire

for {set i 1} {$i <= ["Result.Label-Analysis" getNumRows ]} {set i [expr $i+1]} {

remove "Arithmetic"
remove Result2
remove "Generate Surface"
remove "Result2.surf"
remove "Surface View"

set hideNewModules 0
create HxArithmetic "Arithmetic"
"Arithmetic" setIconPosition 160 504
"Arithmetic" setVar "CustomHelp" {HxArithmetic}
"Arithmetic" inputA connect "Result.filtered"
"Arithmetic" fire
"Arithmetic" resultChannels setIndex 0 0
"Arithmetic" nValues setMinMax 0 -16777216 16777216
"Arithmetic" nValues setValue 0 1
"Arithmetic" expr0 setState A == $i
"Arithmetic" resultType setValue 0
"Arithmetic" resultLocation setValue 0
"Arithmetic" resolution setMinMax 0 1 100000
"Arithmetic" resolution setValue 0 64
"Arithmetic" resolution setMinMax 1 1 100000
"Arithmetic" resolution setValue 1 64
"Arithmetic" resolution setMinMax 2 1 100000
"Arithmetic" resolution setValue 2 64
"Arithmetic" minBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 0 -1
"Arithmetic" minBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 1 -1
"Arithmetic" minBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 2 -1
"Arithmetic" maxBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 0 1
"Arithmetic" maxBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 1 1
"Arithmetic" maxBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 2 1
"Arithmetic" options setValue 0 0
"Arithmetic" options setToggleVisible 0 1
"Arithmetic" applyTransformToResult 1
"Arithmetic" fire
"Arithmetic" setViewerMask 16383
"Arithmetic" setPickable 1

set hideNewModules 0
[ {Arithmetic} create result ] setLabel "Result2"
"Result2" setIconPosition 20 504
"Result2" master connect "Arithmetic" "result" 0
"Result2" sharedColormap connect "labels.am"
"Result2" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result2" sharedColormap setDefaultAlpha 0.500000
"Result2" sharedColormap activateLocalRange 1
"Result2" sharedColormap setLocalMinMax 1.000000 8.000000
"Result2" sharedColormap enableAlpha 1
"Result2" sharedColormap enableAlphaToggle 1
"Result2" sharedColormap setAutoAdjustRangeMode 1
"Result2" sharedColormap setColorbarMinMax 1 8
"Result2" fire
"Result2" primary setIndex 0 0
"Result2" fire
"Result2" setViewerMask 16383

set hideNewModules 0
create HxGMC "Generate Surface"
"Generate Surface" setIconPosition 160 432
"Generate Surface" setVar "CustomHelp" {HxGMC}
"Generate Surface" data connect "Result2"
"Generate Surface" fire
"Generate Surface" smoothing setIndex 0 3
"Generate Surface" smoothingExtent setMinMax 1 9
"Generate Surface" smoothingExtent setButtons 0
"Generate Surface" smoothingExtent setEditButton 1
"Generate Surface" smoothingExtent setIncrement 0.533333
"Generate Surface" smoothingExtent setValue 5
"Generate Surface" smoothingExtent setSubMinMax 1 9
"Generate Surface" options setState {item 0 0 item 1 0 }
"Generate Surface" borderOnOff setValue 1
"Generate Surface" algorithmMode setIndex 0 0
"Generate Surface" borderSettings setValue 0 1
"Generate Surface" borderSettings setToggleVisible 0 1
"Generate Surface" borderSettings setValue 1 0
"Generate Surface" borderSettings setToggleVisible 1 1
"Generate Surface" borderSettings setValue 2 0
"Generate Surface" borderSettings setToggleVisible 2 1
"Generate Surface" borderSettings setValue 3 0
"Generate Surface" borderSettings setToggleVisible 3 0
"Generate Surface" materialList setIndex 0 0
"Generate Surface" smoothMaterial setIndex 0 0
"Generate Surface" applyTransformToResult 1
"Generate Surface" fire
"Generate Surface" setViewerMask 16383
"Generate Surface" setPickable 1

set hideNewModules 0
[ "Generate Surface" create "Result2.surf"
 ] setLabel "Result2.surf"
 "Result2.surf" setIconPosition 20 432
 "Result2.surf" master connect "Generate Surface" "result" 0
 "Result2.surf" fire
 "Result2.surf" LevelOfDetail setMinMax -1 -1
 "Result2.surf" LevelOfDetail setButtons 1
 "Result2.surf" LevelOfDetail setEditButton 1
 "Result2.surf" LevelOfDetail setIncrement 1
 "Result2.surf" LevelOfDetail setValue -1
 "Result2.surf" LevelOfDetail setSubMinMax -1 -1
 "Result2.surf" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
 "Result2.surf" fire
 "Result2.surf" setViewerMask 16383
 
 "Result2.surf" exportData "Stanford PLY" D:/data/MDean/${param}.label$i.surf
 
 set hideNewModules 0
 create HxDisplaySurface "Surface View"
 "Surface View" setIconPosition -37 468
 "Surface View" setVar "CustomHelp" {HxDisplaySurface}
 "Surface View" data connect "Result2.surf"
 "Surface View" colormap disconnect
 "Surface View" colormap setDefaultColor 1 0.1 0.1
 "Surface View" colormap setDefaultAlpha 0.500000
 "Surface View" colormap activateLocalRange 1
 "Surface View" colormap setLocalMinMax 0.000000 1.000000
 "Surface View" colormap enableAlpha 1
 "Surface View" colormap enableAlphaToggle 1
 "Surface View" colormap setAutoAdjustRangeMode 1
 "Surface View" colormap setColorbarMinMax 0 120
 "Surface View" fire
 "Surface View" drawStyle setValue 2
 "Surface View" fire
 "Surface View" drawStyle setSpecularLighting 1
 "Surface View" drawStyle setTexture 1
 "Surface View" drawStyle setAlphaMode 3
 "Surface View" drawStyle setCullingMode 0
 "Surface View" drawStyle setNormalBinding 0
 "Surface View" drawStyle setSortingMode 1
 "Surface View" drawStyle setLineWidth 1.000000
 "Surface View" drawStyle setOutlineColor 0 0 0.2
 "Surface View" textureWrap setIndex 0 1
 "Surface View" selectionMode setIndex 0 0
 "Surface View" patch setMinMax 0 1
 "Surface View" patch setButtons 1
 "Surface View" patch setEditButton 1
 "Surface View" patch setIncrement 1
 "Surface View" patch setValue 0
 "Surface View" patch setSubMinMax 0 1
 "Surface View" boundaryId setIndex 0 -1
 "Surface View" materials setIndex 0 1
 "Surface View" materials setIndex 1 0
 "Surface View" colorMode setIndex 0 0
 "Surface View" baseTrans setMinMax 0 1
 "Surface View" baseTrans setButtons 0
 "Surface View" baseTrans setEditButton 1
 "Surface View" baseTrans setIncrement 0.1
 "Surface View" baseTrans setValue 0.8
 "Surface View" baseTrans setSubMinMax 0 1
 "Surface View" VRMode setIndex 0 0
 "Surface View" colorFieldMappingType setValue 0
 "Surface View" setLighting 1
 "Surface View" fire
 "Surface View" hideBox 1
 "Surface View" selectTriangles zab HIJMONMDDBANAAAAAMADCAAJPDKPLGKLIKFOJAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAHCPNMLJONCJA
 "Surface View" fire
 "Surface View" setViewerMask 16383
 "Surface View" select
 "Surface View" setShadowStyle 3
 "Surface View" setPickable 1
 
 set hideNewModules 1
 create HxDataDirectory "DataDirectory_Result2"
 "DataDirectory_Result2" setIconPosition 0 0
 "DataDirectory_Result2" setInvisible 1
 "DataDirectory_Result2" parentDir connect "Data"
 "DataDirectory_Result2" attachedData connect "Result2"
 "DataDirectory_Result2" fire
 "DataDirectory_Result2" setViewerMask 16383
 
 set hideNewModules 1
 create HxDataDirectory "DataDirectory_Result2.surf"
 "DataDirectory_Result2.surf" setIconPosition 0 0
 "DataDirectory_Result2.surf" setInvisible 1
 "DataDirectory_Result2.surf" parentDir connect "Data"
 "DataDirectory_Result2.surf" attachedData connect "Result2.surf"
 "DataDirectory_Result2.surf" fire
 "DataDirectory_Result2.surf" setViewerMask 16383
 
 set hideNewModules 0
 
 "Voxelized Rendering" colormapLookup setValue 0
 "VoxelizedRendering" fire
 viewer 0 redraw
 
 viewer snapshot -offscreen 640 640 D:/data/MDean/${param}.label$i.surface.png
 }
 
 set hideNewModules 0
 create HxArithmetic "Arithmetic_Medulla"
 "Arithmetic_Medulla" setIconPosition 160 504
 "Arithmetic_Medulla" setVar "CustomHelp" {HxArithmetic}
 "Arithmetic_Medulla" inputA connect "Result.filtered"
 "Arithmetic_Medulla" inputB connect "Result.opening"
 "Arithmetic_Medulla" fire
 "Arithmetic_Medulla" resultChannels setIndex 0 0
 "Arithmetic_Medulla" nValues setMinMax 0 -16777216 16777216
 "Arithmetic_Medulla" nValues setValue 0 1
 "Arithmetic_Medulla" expr0 setState (B == 0) * A
 "Arithmetic_Medulla" resultType setValue 0
 "Arithmetic_Medulla" resultLocation setValue 0
 "Arithmetic_Medulla" resolution setMinMax 0 1 100000
 "Arithmetic_Medulla" resolution setValue 0 64
 "Arithmetic_Medulla" resolution setMinMax 1 1 100000
 "Arithmetic_Medulla" resolution setValue 1 64
 "Arithmetic_Medulla" resolution setMinMax 2 1 100000
 "Arithmetic_Medulla" resolution setValue 2 64
 "Arithmetic_Medulla" minBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" minBox setValue 0 -1
 "Arithmetic_Medulla" minBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" minBox setValue 1 -1
 "Arithmetic_Medulla" minBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" minBox setValue 2 -1
 "Arithmetic_Medulla" maxBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" maxBox setValue 0 1
 "Arithmetic_Medulla" maxBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" maxBox setValue 1 1
 "Arithmetic_Medulla" maxBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
 "Arithmetic_Medulla" maxBox setValue 2 1
 "Arithmetic_Medulla" options setValue 0 0
 "Arithmetic_Medulla" options setToggleVisible 0 1
 "Arithmetic_Medulla" applyTransformToResult 1
 "Arithmetic_Medulla" fire
 "Arithmetic_Medulla" setViewerMask 16383
 "Arithmetic_Medulla" setPickable 1
 
 set hideNewModules 0
 [ {Arithmetic_Medulla} create result ] setLabel "Result2_Medulla"
 "Result2_Medulla" setIconPosition 20 504
 "Result2_Medulla" master connect "Arithmetic_Medulla" "result" 0
 "Result2_Medulla" sharedColormap connect "labels.am"
 "Result2_Medulla" sharedColormap setDefaultColor 0.8 0.8 0.8
 "Result2_Medulla" sharedColormap setDefaultAlpha 0.500000
 "Result2_Medulla" sharedColormap activateLocalRange 1
 "Result2_Medulla" sharedColormap setLocalMinMax 1.000000 8.000000
 "Result2_Medulla" sharedColormap enableAlpha 1
 "Result2_Medulla" sharedColormap enableAlphaToggle 1
 "Result2_Medulla" sharedColormap setAutoAdjustRangeMode 1
 "Result2_Medulla" sharedColormap setColorbarMinMax 1 8
 "Result2_Medulla" fire
 "Result2_Medulla" primary setIndex 0 0
 "Result2_Medulla" fire
 "Result2_Medulla" setViewerMask 16383
 
 set hideNewModules 0
 create sphereclosing3d "Opening_Medulla"
 "Opening_Medulla" setIconPosition 160 540
 "Opening_Medulla" setVar "CustomHelp" {sphereopening3d.html}
 "Opening_Medulla" Type setState {type Ball}
 "Opening_Medulla" interpretation setValue 0
 "Opening_Medulla" outputLocation setIndex 0 0
 "Opening_Medulla" inputImage connect "Result2_Medulla"
 "Opening_Medulla" size setMinMax 0 1 2147483648
 "Opening_Medulla" size setValue 0 20
 "Opening_Medulla" precision setIndex 0 0
 "Opening_Medulla" applyTransformToResult 1
 "Opening_Medulla" fire
 "Opening_Medulla" setViewerMask 16383
 "Opening_Medulla" setPickable 1
 
 set hideNewModules 0
 [ {Opening_Medulla} create ImgOut ] setLabel "Result.opening_Medulla"
 "Result.opening_Medulla" setIconPosition 20 540
 "Result.opening_Medulla" master connect "Selective opening_Medulla" "ImgOut" 0
 "Result.opening_Medulla" sharedColormap connect "labels.am"
 "Result.opening_Medulla" sharedColormap setDefaultColor 0.8 0.8 0.8
 "Result.opening_Medulla" sharedColormap setDefaultAlpha 0.500000
 "Result.opening_Medulla" sharedColormap activateLocalRange 1
 "Result.opening_Medulla" sharedColormap setLocalMinMax 1.000000 8.000000
 "Result.opening_Medulla" sharedColormap enableAlpha 1
 "Result.opening_Medulla" sharedColormap enableAlphaToggle 1
 "Result.opening_Medulla" sharedColormap setAutoAdjustRangeMode 1
 "Result.opening_Medulla" sharedColormap setColorbarMinMax 1 8
 "Result.opening_Medulla" fire
 "Result.opening_Medulla" primary setIndex 0 0
 "Result.opening_Medulla" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
 "Result.opening_Medulla" fire
 "Result.opening_Medulla" setViewerMask 16383
 
 set hideNewModules 0
 create HxAnalyzeLabels "Label Analysis_Medulla"
 "Label Analysis_Medulla" setIconPosition 160 324
 "Label Analysis_Medulla" setVar "CustomHelp" {HxAnalyzeLabels}
 "Label Analysis_Medulla" data connect "Result.opening_Medulla"
 "Label Analysis_Medulla" fire
 "Label Analysis_Medulla" interpretation setValue 0
 "Label Analysis_Medulla" sequenceMode setValue 0
 labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
 labelMeasure setAttributes feret3d 31
 labelMeasure setAttributes cooccurrence 0 0
 labelMeasure setAttributes histogram 1 0 255 1
 labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
 labelMeasure setAttributes breadth3d 10
 labelMeasure setAttributes neighborCount 0 5 0
 "Label Analysis_Medulla" measures setState {"Geometry"}
 "Label Analysis_Medulla" showAnalysis setValue 0 1
 "Label Analysis_Medulla" showAnalysis setToggleVisible 0 1
 "Label Analysis_Medulla" applyTransformToResult 1
 "Label Analysis_Medulla" fire
 "Label Analysis_Medulla" setViewerMask 16383
 "Label Analysis_Medulla" setPickable 1
 
 set hideNewModules 0
 [ {Label Analysis_Medulla} create AnlOut ] setLabel "Result.Label-Analysis_Medulla"
 "Result.Label-Analysis_Medulla" setIconPosition 20 360
 "Result.Label-Analysis_Medulla" master connect "Label Analysis_Medulla" "AnlOut" 0
 "Result.Label-Analysis_Medulla" fire
 "Result.Label-Analysis_Medulla" fire
 "Result.Label-Analysis_Medulla" setViewerMask 16383
 
 set hideNewModules 1
 create HxDataDirectory "DataDirectory_Result.Label-Analysis_Medulla"
 "DataDirectory_Result.Label-Analysis_Medulla" setIconPosition 0 0
 "DataDirectory_Result.Label-Analysis_Medulla" setInvisible 1
 "DataDirectory_Result.Label-Analysis_Medulla" setVar "CustomHelp" {HxDataDirectory}
 "DataDirectory_Result.Label-Analysis_Medulla" parentDir connect "Data"
 "DataDirectory_Result.Label-Analysis_Medulla" attachedData connect "Result.opening_Medulla"
 "DataDirectory_Result.Label-Analysis_Medulla" fire
 "DataDirectory_Result.Label-Analysis_Medulla" setViewerMask 16383
 
 set hideNewModules 1
 create HxDataDirectory "DataDirectory_Result2_Medulla"
 "DataDirectory_Result2_Medulla" setIconPosition 0 0
 "DataDirectory_Result2_Medulla" setInvisible 1
 "DataDirectory_Result2_Medulla" parentDir connect "Data"
 "DataDirectory_Result2_Medulla" attachedData connect "Result2_Medulla"
 "DataDirectory_Result2_Medulla" fire
 "DataDirectory_Result2_Medulla" setViewerMask 16383
 
 "Result.Label-Analysis_Medulla" exportData "csv"  D:/data/MDean/MDean_baculae.${param}.label_analysis_Medulla.csv
 
 theObjectPool setSelectionOrder {Surface View}
 "Colormaps" collapse
 quit